apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: back-ns
spec:
  limits:
  - default: # default value
      cpu: 150m
      memory: 256Mi
    defaultRequest: # default request
      cpu: 100m
      memory: 128Mi
    max: # max limit that the container can set
      cpu: 300m
      memory: 500Mi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container