
# kubectl config set-context --current --namespace=deployment-lab

apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
  namespace: deployment-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-deploy-lab
      track: canary
  template:
    metadata:
      name: hr-deployment-lab
      labels:
        app: hr-deploy-lab
        track: canary
    spec:
      containers:
      - name: hruicontainer
        image: mtahaelmaghrabi/hrmvc:v8.0
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: "app/Logs"
          name: volume
      volumes:
      - name: volume # in case of Dynamic volumes
        emptyDir: {}